### ISSUE TITLE
無法交易 SlimeFun 物品

### ISSUE THREAD

**Issue by HeyNight0712** [ybw0014/VillagerTrade#18]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/ybw0014/VillagerTrade/issues)，且没有找到相同的问题

### 问题描述

會一直顯示 不能使用 SlimeFun 物品進行村名交易
![image](https://github.com/ybw0014/VillagerTrade/assets/97263430/1ac1d427-6436-4b32-b00a-52763a0723aa)

### 复现步骤

與村名交易 使用 SlimeFun 進行交易
![image](https://github.com/ybw0014/VillagerTrade/assets/97263430/ba210729-7c72-45bd-b99d-291ecf213408)

### 预期行为

無法判定交易內容? 可能只是對於有slimefun標籤進行處置

### 服务端软件

Spigot

### Minecraft 版本

1.19.x

### Slimefun版本

Slimefun-v2023.06-release.jar
![image](https://github.com/ybw0014/VillagerTrade/assets/97263430/58e4cb3b-842b-4fed-8eb5-43c6be984c73)

### 插件版本

72cda

**Comment by ybw0014** [comment]
粘液科技会阻止粘液物品在交易界面的背包点击，然后会提示该消息。本插件取消了点击限制但是无法取消消息提示。你可以无视该消息，或者使用左侧选择交易来避免触发该消息。

**Comment by ybw0014** [comment]
等 https://github.com/Slimefun/Slimefun4/pull/3832 合并了这问题就能解决了
